site_name: Ongoing Dwarf Fortress Strategy Guide
site_url: https://redhalo.github.io/df-strategy
site_author: Robert McCoy

repo_name: redhalo/df-strategy
repo_url: https://github.com/redhalo/df-strategy

theme:
  name: material
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: brown
      accent: deep orange
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: brown
      accent: deep orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

  font:
    text: Noto Sans
    code: Noto Sans Mono

  icon:
    logo: material/pickaxe
    repo: fontawesome/brands/github

  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.tracking
    - navigation.path
    - navigation.indexes
    - toc.follow
    - toc.integration
    - navigation.top
    - search.support
    - header.autohide
    - navigation.footer
    - content.action.edit

plugins:
  - search
  - git-revision-date-localized:
      enable_creation_date: true
  - git-authors

markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

