site_name: An Ongoing Dwarf Fortress Strategy Guide
site_url: https://redhalo.github.io/df-strategy
site_description: An ongoing Dwarf Fortress strategy guide.
site_author: Robert McCoy
copyright: This work is marked with [CC0 1.0 :fontawesome-brands-creative-commons::fontawesome-brands-creative-commons-zero:](https://creativecommons.org/publicdomain/zero/1.0/?ref=chooser-v1)

repo_name: redhalo/df-strategy
repo_url: https://github.com/redhalo/df-strategy

nav:
  - 'index.md'
  - 'starting-new-game.md'

theme:
  name: material
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/link
        name: Switch to light mode
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: brown
      accent: deep orange
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: brown
      accent: deep orange
      toggle:
        icon: material/toggle-switch-off
        name: Switch to system preference

  font:
    text: Roboto
    code: Roboto Mono

  icon:
    logo: material/pickaxe
    repo: fontawesome/brands/github

  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.tracking
    - navigation.path
    - navigation.indexes
    - toc.follow
    - toc.integrate
    - navigation.top
    - search.support
    - header.autohide
    - navigation.footer
    - content.action.view
    - content.action.edit

plugins:
  - search
  - git-revision-date-localized:
      enable_creation_date: true
  - git-authors

markdown_extensions:
  - admonition
  - footnotes
  - tables
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

